import '../models/lore_region.dart';

/// Région officielle de chaque champion.
///
/// FICHIER GÉNÉRÉ par `tool/generate_champion_regions.dart` depuis
/// l'API du site Univers de Riot (Data Dragon 16.18.1).
/// Ne pas éditer à la main : relancer le script.
///
/// Un champion absent d'ici est sorti après la dernière génération ;
/// il apparaît sous « Non répertoriés » sur la carte.
const championRegions = <String, RegionId>{
  // Demacia
  'Fiora': RegionId.demacia,
  'Galio': RegionId.demacia,
  'Garen': RegionId.demacia,
  'JarvanIV': RegionId.demacia,
  'Kayle': RegionId.demacia,
  'Locke': RegionId.demacia,
  'Lux': RegionId.demacia,
  'Morgana': RegionId.demacia,
  'Poppy': RegionId.demacia,
  'Quinn': RegionId.demacia,
  'Shyvana': RegionId.demacia,
  'Sona': RegionId.demacia,
  'Sylas': RegionId.demacia,
  'Vayne': RegionId.demacia,
  'XinZhao': RegionId.demacia,

  // Noxus
  'Ambessa': RegionId.noxus,
  'Briar': RegionId.noxus,
  'Cassiopeia': RegionId.noxus,
  'Darius': RegionId.noxus,
  'Draven': RegionId.noxus,
  'Katarina': RegionId.noxus,
  'Kled': RegionId.noxus,
  'Leblanc': RegionId.noxus,
  'Mel': RegionId.noxus,
  'Mordekaiser': RegionId.noxus,
  'Rell': RegionId.noxus,
  'Riven': RegionId.noxus,
  'Samira': RegionId.noxus,
  'Sion': RegionId.noxus,
  'Swain': RegionId.noxus,
  'Talon': RegionId.noxus,
  'Vladimir': RegionId.noxus,

  // Ionie
  'Ahri': RegionId.ionia,
  'Akali': RegionId.ionia,
  'Hwei': RegionId.ionia,
  'Irelia': RegionId.ionia,
  'Ivern': RegionId.ionia,
  'Jhin': RegionId.ionia,
  'Karma': RegionId.ionia,
  'Kayn': RegionId.ionia,
  'Kennen': RegionId.ionia,
  'LeeSin': RegionId.ionia,
  'Lillia': RegionId.ionia,
  'MasterYi': RegionId.ionia,
  'MonkeyKing': RegionId.ionia,
  'Rakan': RegionId.ionia,
  'Sett': RegionId.ionia,
  'Shen': RegionId.ionia,
  'Syndra': RegionId.ionia,
  'Varus': RegionId.ionia,
  'Xayah': RegionId.ionia,
  'Yasuo': RegionId.ionia,
  'Yone': RegionId.ionia,
  'Yunara': RegionId.ionia,
  'Zed': RegionId.ionia,

  // Freljord
  'Anivia': RegionId.freljord,
  'Ashe': RegionId.freljord,
  'Aurora': RegionId.freljord,
  'Braum': RegionId.freljord,
  'Gnar': RegionId.freljord,
  'Gragas': RegionId.freljord,
  'Lissandra': RegionId.freljord,
  'Nunu': RegionId.freljord,
  'Olaf': RegionId.freljord,
  'Ornn': RegionId.freljord,
  'Sejuani': RegionId.freljord,
  'Trundle': RegionId.freljord,
  'Tryndamere': RegionId.freljord,
  'Udyr': RegionId.freljord,
  'Volibear': RegionId.freljord,

  // Piltover
  'Caitlyn': RegionId.piltover,
  'Camille': RegionId.piltover,
  'Ezreal': RegionId.piltover,
  'Heimerdinger': RegionId.piltover,
  'Jayce': RegionId.piltover,
  'Orianna': RegionId.piltover,
  'Seraphine': RegionId.piltover,
  'Vi': RegionId.piltover,

  // Zaun
  'Blitzcrank': RegionId.zaun,
  'DrMundo': RegionId.zaun,
  'Ekko': RegionId.zaun,
  'Janna': RegionId.zaun,
  'Jinx': RegionId.zaun,
  'Renata': RegionId.zaun,
  'Singed': RegionId.zaun,
  'Twitch': RegionId.zaun,
  'Urgot': RegionId.zaun,
  'Viktor': RegionId.zaun,
  'Warwick': RegionId.zaun,
  'Zac': RegionId.zaun,
  'Zeri': RegionId.zaun,
  'Ziggs': RegionId.zaun,

  // Shurima
  'Akshan': RegionId.shurima,
  'Amumu': RegionId.shurima,
  'Azir': RegionId.shurima,
  'KSante': RegionId.shurima,
  'Naafiri': RegionId.shurima,
  'Nasus': RegionId.shurima,
  'Rammus': RegionId.shurima,
  'Renekton': RegionId.shurima,
  'Sivir': RegionId.shurima,
  'Taliyah': RegionId.shurima,
  'Xerath': RegionId.shurima,

  // Targon
  'Aphelios': RegionId.targon,
  'Diana': RegionId.targon,
  'Leona': RegionId.targon,
  'Pantheon': RegionId.targon,
  'Soraka': RegionId.targon,
  'Taric': RegionId.targon,
  'Zoe': RegionId.targon,

  // Bilgewater
  'Gangplank': RegionId.bilgewater,
  'Graves': RegionId.bilgewater,
  'Illaoi': RegionId.bilgewater,
  'MissFortune': RegionId.bilgewater,
  'Nautilus': RegionId.bilgewater,
  'Nilah': RegionId.bilgewater,
  'Pyke': RegionId.bilgewater,
  'TwistedFate': RegionId.bilgewater,

  // Îles Obscures
  'Elise': RegionId.shadowIsles,
  'Gwen': RegionId.shadowIsles,
  'Hecarim': RegionId.shadowIsles,
  'Kalista': RegionId.shadowIsles,
  'Karthus': RegionId.shadowIsles,
  'Maokai': RegionId.shadowIsles,
  'Thresh': RegionId.shadowIsles,
  'Vex': RegionId.shadowIsles,
  'Viego': RegionId.shadowIsles,
  'Yorick': RegionId.shadowIsles,

  // Ixtal
  'Malphite': RegionId.ixtal,
  'Milio': RegionId.ixtal,
  'Neeko': RegionId.ixtal,
  'Nidalee': RegionId.ixtal,
  'Qiyana': RegionId.ixtal,
  'Rengar': RegionId.ixtal,
  'Skarner': RegionId.ixtal,
  'Zyra': RegionId.ixtal,

  // Bandle
  'Corki': RegionId.bandleCity,
  'Lulu': RegionId.bandleCity,
  'Rumble': RegionId.bandleCity,
  'Teemo': RegionId.bandleCity,
  'Tristana': RegionId.bandleCity,
  'Veigar': RegionId.bandleCity,
  'Yuumi': RegionId.bandleCity,

  // Néant
  'Belveth': RegionId.theVoid,
  'Chogath': RegionId.theVoid,
  'Kaisa': RegionId.theVoid,
  'Kassadin': RegionId.theVoid,
  'Khazix': RegionId.theVoid,
  'KogMaw': RegionId.theVoid,
  'Malzahar': RegionId.theVoid,
  'RekSai': RegionId.theVoid,
  'Velkoz': RegionId.theVoid,

  // Sans attache (aucune nation dans l'univers officiel)
  'Aatrox': RegionId.runeterra,
  'Alistar': RegionId.runeterra,
  'Annie': RegionId.runeterra,
  'AurelionSol': RegionId.runeterra,
  'Bard': RegionId.runeterra,
  'Brand': RegionId.runeterra,
  'Evelynn': RegionId.runeterra,
  'Fiddlesticks': RegionId.runeterra,
  'Fizz': RegionId.runeterra,
  'Jax': RegionId.runeterra,
  'Kindred': RegionId.runeterra,
  'Lucian': RegionId.runeterra,
  'Nami': RegionId.runeterra,
  'Nocturne': RegionId.runeterra,
  'Ryze': RegionId.runeterra,
  'Senna': RegionId.runeterra,
  'Shaco': RegionId.runeterra,
  'Smolder': RegionId.runeterra,
  'TahmKench': RegionId.runeterra,
  'Zaahen': RegionId.runeterra,
  'Zilean': RegionId.runeterra,
};
